# Generated by Django 3.1 on 2021-05-04 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=150)),
                ('social_type', models.IntegerField(choices=[(1, 'Linkedin'), (2, 'Facebook'), (3, 'Google')])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='social_account')),
            ],
            options={
                'verbose_name': 'Social account',
                'verbose_name_plural': 'Social accounts',
                'db_table': 'social_account',
            },
        ),
    ]
